FROM node:22-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm --filter=shared install

RUN pnpm --filter=frontend install
RUN pnpm --filter=frontend run build

FROM nginx:alpine

COPY --from=build /app/apps/frontend/dist /usr/share/nginx/html

COPY ./apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]