FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY . .

RUN pnpm --filter=shared install
RUN pnpm --filter=shared run build

RUN pnpm --filter=backend deploy /prod/backend

WORKDIR /prod/backend

RUN pnpm run build

EXPOSE 8080

CMD ["bash", "./start.sh"]